name: synthseg_raven
channels:
  - defaults
  - conda-forge
dependencies:
  # trying to emulate following env on raven:
  # >module load anaconda/3/2021.11 tensorflow/gpu-cuda-11.6/2.11.0 scikit-learn/1.1.1
  - python=3.9.7
  - cudatoolkit=11.6.0
  - cudnn=8.4.1
  - tensorflow-gpu=2.11.0
  - scikit-learn=1.1.1
  - tqdm=4.62.3
  - matplotlib=3.4.3
  - ipython=7.29.0
  - pip=21.2.4
  # on raven you should install the requirements in an "venv" after loading the modules
  # >python -m venv --system-site-packages ~/venvs/synthseg
  # >source ~/venvs/synthseg/bin/activate
  # >pip install -r requirements_raven.txt
  - pip:
      - -r requirements_raven.txt
